version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: web-server
    volumes:
      - ./frontend:/app
    ports:
      - "5000:5000"

  # backend:
  #   build: ./backend
  #   container_name: api-server
  #   volumes:
  #     - ./backend:/app
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - mysql
  #     - mongodb
  #   networks:
  #     - movieconnect

  mysql: # 유저 정보 등
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=movies
    volumes:
      - ./database/mysql_data:/var/lib/mysql
    ports:
      - "3307:3307"

  mongodb: # 게시물 정보 등
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./database/mongodb_data:/data/db
    ports:
      - "27017:27017"
